server.port=8081

spring.data.mongodb.uri=mongodb+srv://bhaskar4843:bhaskar13@cluster0.5jah0ea.mongodb.net/jobportal?retryWrites=true&w=majority

spring.web.resources.static-locations=file:///D:/JOB%20PORTAL/backend/jobportal/uploads/,classpath:/static/

jobportal.recruiter-registration-code=DreamJob@12